version: '3.8'

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    volumes:
      - ./reverse-proxy/dev/ssl:/etc/nginx/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - gateway

networks:
  gateway:
    name: gateway
    external: true
