version: '3.8'

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    image: ${IMAGE_REGISTRY:-local}/gateway-reverse-proxy:${IMAGE_TAG:-latest}
    volumes:
      # SSL certificates folder (shared with certbot service)
      - ./reverse-proxy/ssl:/etc/nginx/ssl:ro
      # ACME challenge folder (shared with certbot service)
      - ./reverse-proxy/acme:/var/www/acme:ro
    expose:
      - 8001
    ports:
      - "443:443"
      - "80:80"
    networks:
      - gateway
    restart: unless-stopped

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    image: ${IMAGE_REGISTRY:-local}/gateway-certbot:${IMAGE_TAG:-latest}
    environment:
      NGINX_SERVICE: reverse-proxy
    volumes:
      # SSL certificates folder
      - ./reverse-proxy/ssl:/etc/letsencrypt:rw
      # ACME challenge folder
      - ./reverse-proxy/acme:/var/www/acme:rw
      # Docker Unix Socket (allow restarting reverse-proxy service after renewal)
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped

networks:
  gateway:
    name: gateway
    external: true
